/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as SCodeMeRouteImport } from './routes/s.$code.me'
import { Route as SCodeReportRouteImport } from './routes/s.$code.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SCodeMeRoute = SCodeMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => SCodeRoute,
} as any)
const SCodeReportRoute = SCodeReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => SCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s/$code': typeof SCodeRouteWithChildren
  '/s/$code/me': typeof SCodeMeRoute
  '/s/$code/report': typeof SCodeReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s/$code': typeof SCodeRouteWithChildren
  '/s/$code/me': typeof SCodeMeRoute
  '/s/$code/report': typeof SCodeReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/s/$code': typeof SCodeRouteWithChildren
  '/s/$code/me': typeof SCodeMeRoute
  '/s/$code/report': typeof SCodeReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/s/$code' | '/s/$code/me' | '/s/$code/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/s/$code' | '/s/$code/me' | '/s/$code/report'
  id: '__root__' | '/' | '/s/$code' | '/s/$code/me' | '/s/$code/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SCodeRoute: typeof SCodeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$code/me': {
      id: '/s/$code/me'
      path: '/me'
      fullPath: '/s/$code/me'
      preLoaderRoute: typeof SCodeMeRouteImport
      parentRoute: typeof SCodeRoute
    }
    '/s/$code/report': {
      id: '/s/$code/report'
      path: '/report'
      fullPath: '/s/$code/report'
      preLoaderRoute: typeof SCodeReportRouteImport
      parentRoute: typeof SCodeRoute
    }
  }
}

interface SCodeRouteChildren {
  SCodeMeRoute: typeof SCodeMeRoute
  SCodeReportRoute: typeof SCodeReportRoute
}

const SCodeRouteChildren: SCodeRouteChildren = {
  SCodeMeRoute: SCodeMeRoute,
  SCodeReportRoute: SCodeReportRoute,
}

const SCodeRouteWithChildren = SCodeRoute._addFileChildren(SCodeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SCodeRoute: SCodeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
